live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 100000

[font]
normal = { family = "SFMono Nerd Font" }

[window]
opacity = 0.97
dynamic_title = true
dynamic_padding = true
blur = true
