"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$character
"""
add_newline = false
command_timeout = 5000

[character]
success_symbol = '[➜](bold green)'

[git_branch]
symbol = ''

