"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$character\
$cmd_duration\
"""

#format = """
#$username@\
#$hostname\
#$directory\
#$git_branch\
#$git_commit\
#$git_state\
#$git_metrics\
#$git_status\
#$package\
#$character\
#$cmd_duration\
#"""
add_newline = false

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[git_branch]
symbol = ''


[package]
display_private = false
disabled = false


[cmd_duration]
min_time = 5_000
format = "took [$duration](bold blue)"

[username]
show_always = true
format = "[$user](bold blue)"

[hostname]
ssh_only = true
trim_at = ".local"
format = "@[$hostname](bold green) "

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1
truncation_symbol = "…/"
